PT-2045  Rename custom attribute to avoid the ambiguity to AllowedValuesValidation to fix issue Error CS0104 : 'AllowedValues' is an ambiguous reference between 'ApplicationAcquisitionSubmissions.Contract.DataAttributes.AllowedValuesAttribute' and 'System.ComponentModel.DataAnnotations.AllowedValuesAttribute' - .NET 8 added a built-in AllowedValuesAttribute to System.ComponentModel.DataAnnotations, which is conflicting with your custom one.